### ISSUE TITLE
mac系统上好像没html文件

### ISSUE THREAD

**Issue by bantaotiehe** [PeggyZWY/house-renting-spider#4]
我今天下载了下，在mac版本上跑了下，跑成功了，但是在results里只有.splite文件，没有生成html文件，请问是怎么回事呢，是需要改哪些配置么

**Comment by PeggyZWY** [comment]
你好！我按照README从自己的github上重新下载，运行了一遍，没有问题。建议你修改config.ini里的start_time，否则时间太久也没必要，其他的不用修改。如果有问题再联系我。

**Comment by zaofengzhou** [comment]
我生成的html文件里没内容，是怎么回事？
