### ISSUE TITLE
import ConfigParser，找不到对应的库

### ISSUE THREAD

**Issue by JustZeroX** [PeggyZWY/house-renting-spider#6]
请问import ConfigParser，这个库是哪个具体库呢？
import失败了。

**Comment by PeggyZWY** [comment]
你好！ConfigParser 是 Python 2 标准库里的，应该不会有问题的。

['The ancient ConfigParser module available in the standard library 2.x ...'](https://pypi.org/project/configparser/)

**Comment by PeggyZWY** [comment]
如果还是不行你可以把 ini 文件自己改成普通 txt 来配置（再改点代码），就用不上这个库解析了。

如果有空我也可以改一下代码。
